import { Fragment, isValidElement } from 'react';
import type { ReactNode } from 'react';

import { CHAPTERS } from './index';
import type { Chapter } from './index';

export interface SearchResult {
  chapter: Chapter;
  /** Plain-text excerpt around the first match, for the result list. */
  snippet: string;
  /** True when the match is in the chapter's label/group, not its body. */
  titleMatch: boolean;
}

interface IndexEntry {
  chapter: Chapter;
  /** Lowercased, tag-stripped body text of the rendered chapter. */
  text: string;
}

let cached: IndexEntry[] | null = null;

/**
 * Walks a React element tree collecting text, evaluating function components
 * along the way instead of only reading `children`. A chapter is a tree of
 * elements like `<Table headers={...} rows={...} />` whose visible text is
 * *generated by Table's own function body* from those props, not carried in
 * a `children` prop — so text extraction has to call `type(props)` for any
 * element whose `type` is a function and keep walking, the same evaluation
 * React's own renderer would do.
 *
 * This deliberately never touches React's actual renderer (no `createRoot`,
 * no `flushSync`, no DOM). Every chapter and every primitive in
 * `../primitives.tsx` is hook-free, so calling one directly, outside of any
 * render pass, is safe — and it has to be able to run from inside another
 * component's render (the search box builds this index on the first
 * keystroke), where `flushSync` is a hazard: called while React is already
 * rendering, the child render does not commit before the call returns, and
 * an earlier version of this file read back an empty string on every search
 * as a result. A plain function call has no such timing to get wrong.
 */
function textOf(node: ReactNode): string {
  if (node == null || typeof node === 'boolean') return '';
  if (typeof node === 'string' || typeof node === 'number') return `${node} `;
  if (Array.isArray(node)) return node.map(textOf).join('');
  if (!isValidElement(node)) return '';

  const { type, props } = node as { type: unknown; props: { children?: ReactNode } };
  if (type === Fragment || typeof type === 'string') return textOf(props?.children);
  if (typeof type === 'function') return textOf((type as (p: unknown) => ReactNode)(props));
  return textOf(props?.children);
}

function renderToText(Component: Chapter['Component']): string {
  const element = (Component as unknown as () => ReactNode)();
  return textOf(element).replace(/\s+/g, ' ').trim().toLowerCase();
}

/**
 * A plain-text search index built from the same chapter components the page
 * renders, not a hand-maintained keyword list beside them. `PageOutline` in
 * DocsPage.tsx already makes this call for the "on this page" rail — a
 * declared second copy of a chapter's content is a second source of truth
 * that goes stale the moment the chapter is edited and nobody remembers to
 * update the copy.
 *
 * Built lazily, on first search, and cached for the session — chapter
 * content does not change without a reload, so there is nothing to
 * invalidate the cache on.
 */
function getSearchIndex(): IndexEntry[] {
  if (cached) return cached;
  cached = CHAPTERS.map((chapter) => ({ chapter, text: renderToText(chapter.Component) }));
  return cached;
}

const SNIPPET_RADIUS = 70;
const MAX_RESULTS = 12;

function snippetAround(text: string, matchIndex: number, matchLength: number): string {
  const start = Math.max(0, matchIndex - SNIPPET_RADIUS);
  const end = Math.min(text.length, matchIndex + matchLength + SNIPPET_RADIUS);
  const prefix = start > 0 ? '…' : '';
  const suffix = end < text.length ? '…' : '';
  return prefix + text.slice(start, end).trim() + suffix;
}

/** Chapters whose label, group or body contains `query`, ranked and excerpted. */
export function searchChapters(query: string): SearchResult[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const results: SearchResult[] = [];
  for (const { chapter, text } of getSearchIndex()) {
    const titleMatch =
      chapter.label.toLowerCase().includes(q) || chapter.group.toLowerCase().includes(q);
    const bodyIndex = text.indexOf(q);
    if (!titleMatch && bodyIndex === -1) continue;

    const snippet = bodyIndex === -1 ? text.slice(0, 140) : snippetAround(text, bodyIndex, q.length);
    results.push({ chapter, snippet, titleMatch });
  }

  // Title/group matches first; original reading order otherwise, since that
  // is already curated by how central a chapter is to the platform.
  results.sort((a, b) => (a.titleMatch === b.titleMatch ? 0 : a.titleMatch ? -1 : 1));
  return results.slice(0, MAX_RESULTS);
}
