"""services/docs.py: word-overlap search over the exported docs index.

The real `data/docs_index.json` (generated by
`frontend/scripts/export-docs-index.ts`) is used where a test wants to check
against real chapter content; a synthetic index is used where the test cares
about ranking/scoring behaviour rather than any particular chapter's prose.
"""

from __future__ import annotations

from services import docs


def _use_index(monkeypatch, chapters: list[dict[str, str]]) -> None:
    monkeypatch.setattr(docs, "_cache", [docs.DocChapter(**entry) for entry in chapters])


def test_a_real_query_finds_the_map_reading_chapter():
    results = docs.search("how do I read the colours on the map")
    assert results
    assert any(r["chapter"] == "Reading the map" for r in results)
    assert all(r["url"].startswith("/docs?c=") for r in results)


def test_an_empty_query_finds_nothing():
    assert docs.search("") == []
    assert docs.search("   ") == []


def test_a_query_matching_nothing_finds_nothing():
    assert docs.search("xylophone quokka zzzzz") == []


def test_a_title_match_outranks_a_body_only_match(monkeypatch):
    _use_index(
        monkeypatch,
        [
            {
                "id": "a",
                "label": "Eddies",
                "title": "Eddies",
                "group": "Ocean & atmosphere",
                "url": "/docs?c=a",
                "text": "This chapter is about rotating currents and mentions eddies only once in passing.",
            },
            {
                "id": "b",
                "label": "Something else",
                "title": "Something else",
                "group": "Other",
                "url": "/docs?c=b",
                "text": "eddies eddies eddies eddies",
            },
        ],
    )
    results = docs.search("eddies")
    assert results[0]["chapter"] == "Eddies"


def test_the_snippet_centres_on_the_first_match_not_the_chapter_start(monkeypatch):
    long_prefix = "General framing text that never mentions the query term. " * 10
    _use_index(
        monkeypatch,
        [
            {
                "id": "a",
                "label": "Grounding",
                "title": "Grounding",
                "group": "Using the platform",
                "url": "/docs?c=a",
                "text": f"{long_prefix}Grounded means every number traces to a tool result.",
            }
        ],
    )
    result = docs.search("what does grounded mean")[0]
    assert "grounded means every number" in result["snippet"].lower()


def test_limit_caps_the_number_of_results(monkeypatch):
    _use_index(
        monkeypatch,
        [
            {
                "id": str(i),
                "label": f"Chapter {i}",
                "title": f"Chapter {i}",
                "group": "Group",
                "url": f"/docs?c={i}",
                "text": "forecast forecast forecast",
            }
            for i in range(5)
        ],
    )
    assert len(docs.search("forecast", limit=2)) == 2


def test_a_missing_index_file_degrades_to_no_results(monkeypatch, tmp_path):
    monkeypatch.setattr(docs, "_INDEX_PATH", tmp_path / "does-not-exist.json")
    monkeypatch.setattr(docs, "_cache", None)
    assert docs.search("anything") == []
