"""add chat sessions and messages

Revision ID: 0148ba922c31
Revises: 0adac5dcd6eb
Create Date: 2026-08-05 16:57:22.323404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0148ba922c31'
down_revision: Union[str, Sequence[str], None] = '0adac5dcd6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate emits the tables but never the schema that holds them, so
    # this has to be added by hand or the first CREATE TABLE fails on a fresh
    # database. `core` and `observations` were created the same way.
    op.execute("CREATE SCHEMA IF NOT EXISTS chat")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    schema='chat'
    )
    op.create_index('ix_sessions_client_id_updated_at', 'sessions', ['client_id', 'updated_at'], unique=False, schema='chat')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('unsupported_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat.sessions.id'], name=op.f('fk_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('seq', name=op.f('uq_messages_seq')),
    schema='chat'
    )
    op.create_index('ix_messages_session_id_seq', 'messages', ['session_id', 'seq'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_id_seq', table_name='messages', schema='chat')
    op.drop_table('messages', schema='chat')
    op.drop_index('ix_sessions_client_id_updated_at', table_name='sessions', schema='chat')
    op.drop_table('sessions', schema='chat')
    # ### end Alembic commands ###
    # Empty by now — both tables above are gone. RESTRICT rather than CASCADE
    # so this refuses rather than silently dropping anything added later.
    op.execute("DROP SCHEMA IF EXISTS chat RESTRICT")
