"""initial_schema

Revision ID: 0adac5dcd6eb
Revises: 
Create Date: 2026-07-26 13:05:50.848311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0adac5dcd6eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create PostgreSQL schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS observations")
    
    # Enable PostGIS
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_data_sources_name')),
    schema='core'
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('ocean', sa.String(length=100), nullable=True),
    sa.Column('sea', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('eez', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    schema='core'
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('symbol', name=op.f('uq_units_symbol')),
    schema='core'
    )
    op.create_table('variable_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variable_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_variable_categories_name')),
    schema='core'
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('spatial_resolution', sa.String(length=50), nullable=True),
    sa.Column('temporal_resolution', sa.String(length=50), nullable=True),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['core.data_sources.id'], name=op.f('fk_datasets_source_id_data_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    schema='core'
    )
    op.create_index(op.f('ix_datasets_source_id'), 'datasets', ['source_id'], unique=False, schema='core')
    op.create_table('variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['core.variable_categories.id'], name=op.f('fk_variables_category_id_variable_categories')),
    sa.ForeignKeyConstraint(['unit_id'], ['core.units.id'], name=op.f('fk_variables_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variables')),
    sa.UniqueConstraint('code', name=op.f('uq_variables_code')),
    schema='core'
    )
    op.create_index(op.f('ix_variables_category_id'), 'variables', ['category_id'], unique=False, schema='core')
    op.create_index(op.f('ix_variables_unit_id'), 'variables', ['unit_id'], unique=False, schema='core')
    op.create_table('earthquake_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('usgs_event_id', sa.String(length=100), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('depth_km', sa.Float(), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('tsunami', sa.Boolean(), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['core.datasets.id'], name=op.f('fk_earthquake_events_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['location_id'], ['core.locations.id'], name=op.f('fk_earthquake_events_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_earthquake_events')),
    sa.UniqueConstraint('usgs_event_id', name=op.f('uq_earthquake_events_usgs_event_id')),
    schema='observations'
    )
    op.create_index(op.f('ix_earthquake_events_dataset_id'), 'earthquake_events', ['dataset_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_earthquake_events_location_id'), 'earthquake_events', ['location_id'], unique=False, schema='observations')
    op.create_table('fishing_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.String(length=100), nullable=False),
    sa.Column('vessel_name', sa.String(length=255), nullable=True),
    sa.Column('flag_state', sa.String(length=100), nullable=True),
    sa.Column('vessel_type', sa.String(length=100), nullable=True),
    sa.Column('gear_type', sa.String(length=100), nullable=True),
    sa.Column('speed_knots', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('fishing_hours', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['core.datasets.id'], name=op.f('fk_fishing_activity_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['location_id'], ['core.locations.id'], name=op.f('fk_fishing_activity_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fishing_activity')),
    schema='observations'
    )
    op.create_index(op.f('ix_fishing_activity_dataset_id'), 'fishing_activity', ['dataset_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_fishing_activity_location_id'), 'fishing_activity', ['location_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_fishing_activity_observed_at'), 'fishing_activity', ['observed_at'], unique=False, schema='observations')
    op.create_index(op.f('ix_fishing_activity_vessel_id'), 'fishing_activity', ['vessel_id'], unique=False, schema='observations')
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['core.datasets.id'], name=op.f('fk_observations_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['location_id'], ['core.locations.id'], name=op.f('fk_observations_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    schema='observations'
    )
    op.create_index(op.f('ix_observations_dataset_id'), 'observations', ['dataset_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_observations_location_id'), 'observations', ['location_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False, schema='observations')
    op.create_table('satellite_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_format', sa.String(length=30), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('tile_url', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('bbox_west', sa.Float(), nullable=True),
    sa.Column('bbox_south', sa.Float(), nullable=True),
    sa.Column('bbox_east', sa.Float(), nullable=True),
    sa.Column('bbox_north', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['core.datasets.id'], name=op.f('fk_satellite_products_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satellite_products')),
    schema='observations'
    )
    op.create_index(op.f('ix_satellite_products_dataset_id'), 'satellite_products', ['dataset_id'], unique=False, schema='observations')
    op.create_table('species_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('kingdom', sa.String(length=100), nullable=True),
    sa.Column('phylum', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=100), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('basis_of_record', sa.String(length=100), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['core.datasets.id'], name=op.f('fk_species_occurrences_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['location_id'], ['core.locations.id'], name=op.f('fk_species_occurrences_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species_occurrences')),
    sa.UniqueConstraint('occurrence_id', name=op.f('uq_species_occurrences_occurrence_id')),
    schema='observations'
    )
    op.create_index(op.f('ix_species_occurrences_dataset_id'), 'species_occurrences', ['dataset_id'], unique=False, schema='observations')
    op.create_index(op.f('ix_species_occurrences_location_id'), 'species_occurrences', ['location_id'], unique=False, schema='observations')
    op.create_table('observation_values',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('quality_flag', sa.String(length=20), nullable=True),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.observations.id'], name=op.f('fk_observation_values_observation_id_observations')),
    sa.ForeignKeyConstraint(['variable_id'], ['core.variables.id'], name=op.f('fk_observation_values_variable_id_variables')),
    sa.PrimaryKeyConstraint('observation_id', 'variable_id', name=op.f('pk_observation_values')),
    schema='observations'
    )
    op.create_index(op.f('ix_observation_values_variable_id'), 'observation_values', ['variable_id'], unique=False, schema='observations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_values_variable_id'), table_name='observation_values', schema='observations')
    op.drop_table('observation_values', schema='observations')
    op.drop_index(op.f('ix_species_occurrences_location_id'), table_name='species_occurrences', schema='observations')
    op.drop_index(op.f('ix_species_occurrences_dataset_id'), table_name='species_occurrences', schema='observations')
    op.drop_table('species_occurrences', schema='observations')
    op.drop_index(op.f('ix_satellite_products_dataset_id'), table_name='satellite_products', schema='observations')
    op.drop_table('satellite_products', schema='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations', schema='observations')
    op.drop_index(op.f('ix_observations_location_id'), table_name='observations', schema='observations')
    op.drop_index(op.f('ix_observations_dataset_id'), table_name='observations', schema='observations')
    op.drop_table('observations', schema='observations')
    op.drop_index(op.f('ix_fishing_activity_vessel_id'), table_name='fishing_activity', schema='observations')
    op.drop_index(op.f('ix_fishing_activity_observed_at'), table_name='fishing_activity', schema='observations')
    op.drop_index(op.f('ix_fishing_activity_location_id'), table_name='fishing_activity', schema='observations')
    op.drop_index(op.f('ix_fishing_activity_dataset_id'), table_name='fishing_activity', schema='observations')
    op.drop_table('fishing_activity', schema='observations')
    op.drop_index(op.f('ix_earthquake_events_location_id'), table_name='earthquake_events', schema='observations')
    op.drop_index(op.f('ix_earthquake_events_dataset_id'), table_name='earthquake_events', schema='observations')
    op.drop_table('earthquake_events', schema='observations')
    op.drop_index(op.f('ix_variables_unit_id'), table_name='variables', schema='core')
    op.drop_index(op.f('ix_variables_category_id'), table_name='variables', schema='core')
    op.drop_table('variables', schema='core')
    op.drop_index(op.f('ix_datasets_source_id'), table_name='datasets', schema='core')
    op.drop_table('datasets', schema='core')
    op.drop_table('variable_categories', schema='core')
    op.drop_table('units', schema='core')
    op.drop_table('locations', schema='core')
    op.drop_table('data_sources', schema='core')
    # Remove schemas
    op.execute("DROP SCHEMA IF EXISTS observations CASCADE")
    op.execute("DROP SCHEMA IF EXISTS core CASCADE")
    # ### end Alembic commands ###
