"""add dashboard kpi history

Revision ID: 4cfe6c59327f
Revises: 8c7d4485c807
Create Date: 2026-08-28 21:05:45.357884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfe6c59327f'
down_revision: Union[str, Sequence[str], None] = '8c7d4485c807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate emits the table but never the schema that holds it, so
    # this has to be added by hand or the CREATE TABLE fails on a fresh
    # database — same fix 0148ba922c31 and 8c7d4485c807 needed for their own
    # schemas.
    op.execute("CREATE SCHEMA IF NOT EXISTS dashboard")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points')),
    schema='dashboard'
    )
    op.create_index('ix_points_key_recorded_at', 'points', ['key', 'recorded_at'], unique=False, schema='dashboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_points_key_recorded_at', table_name='points', schema='dashboard')
    op.drop_table('points', schema='dashboard')
    # ### end Alembic commands ###
    # RESTRICT, not CASCADE, deliberately — this refuses rather than
    # silently dropping anything added to the schema later.
    op.execute("DROP SCHEMA IF EXISTS dashboard RESTRICT")
