"""add alert subscriptions

Revision ID: 8c7d4485c807
Revises: 0148ba922c31
Create Date: 2026-08-27 17:47:49.276555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7d4485c807'
down_revision: Union[str, Sequence[str], None] = '0148ba922c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate emits the table but never the schema that holds it, so
    # this has to be added by hand or the CREATE TABLE fails on a fresh
    # database — same fix 0148ba922c31 needed for the `chat` schema.
    op.execute("CREATE SCHEMA IF NOT EXISTS alerts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    schema='alerts'
    )
    op.create_index('ix_subscriptions_client_id', 'subscriptions', ['client_id'], unique=False, schema='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_client_id', table_name='subscriptions', schema='alerts')
    op.drop_table('subscriptions', schema='alerts')
    # ### end Alembic commands ###
    # RESTRICT, not CASCADE, deliberately — this refuses rather than
    # silently dropping anything added to the schema later.
    op.execute("DROP SCHEMA IF EXISTS alerts RESTRICT")
